apiVersion: apps/v1
kind: Deployment
metadata:
  name: conducteur-service
  namespace: fleet-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conducteur-service
  template:
    metadata:
      labels:
        app: conducteur-service
    spec:
      containers:
        - name: conducteur-service
          image: fleet-conducteur-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:adminpassword@postgres-postgresql:5432/conducteurs_db"
            - name: KAFKA_BROKER
              value: "fleet-kafka-kafka-bootstrap:9092"
          livenessProbe:
            httpGet:
              path: /api/conducteurs
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"