apiVersion: apps/v1
kind: Deployment
metadata:
  name: evenement-service
  namespace: fleet-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evenement-service
  template:
    metadata:
      labels:
        app: evenement-service
    spec:
      containers:
        - name: evenement-service
          image: fleet-evenement-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:adminpassword@postgres-postgresql:5432/evenements_db"
            - name: REDIS_URL
              value: "redis://redis-master:6379"
            - name: KAFKA_BROKER
              value: "fleet-kafka-kafka-bootstrap:9092"
            - name: KAFKA_TOPIC_VEHICULES
              value: "fleet.vehicules.events"
            - name: KAFKA_TOPIC_MAINTENANCE
              value: "fleet.maintenance.events"
            - name: KAFKA_TOPIC_GEOFENCING
              value: "fleet.geofencing.alerts"
            - name: KAFKA_TOPIC_NOTIFICATIONS
              value: "fleet.notifications"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"