apiVersion: apps/v1
kind: Deployment
metadata:
  name: localisation-service
  namespace: fleet-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: localisation-service
  template:
    metadata:
      labels:
        app: localisation-service
    spec:
      containers:
        - name: localisation-service
          image: fleet-localisation-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:adminpassword@timescaledb-postgresql:5432/localisation_db"
            - name: KAFKA_BROKER
              value: "fleet-kafka-kafka-bootstrap:9092"
            - name: KAFKA_TOPIC_GEOFENCING
              value: "fleet.geofencing.alerts"
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"