apiVersion: v1
kind: Service
metadata:
  name: localisation-service
  namespace: fleet-management
spec:
  selector:
    app: localisation-service
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP