apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: fleet-management
spec:
  selector:
    app: maintenance-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP