loki-stack:
  loki:
    enabled: true
    isDefault: false
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 7d

  promtail:
    enabled: true
    config:
      snippets:
        pipelineStages:
          - docker: {}
