apiVersion: v1
kind: Service
metadata:
  name: evenement-service
  namespace: fleet-management
spec:
  selector:
    app: evenement-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
