apiVersion: apps/v1
kind: Deployment
metadata:
  name: evenement-service
  namespace: fleet-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evenement-service
  template:
    metadata:
      labels:
        app: evenement-service
    spec:
      containers:
        - name: evenement-service
          image: fleet-evenement-service:latest
          imagePullPolicy: Never   
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/evenements_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "adminpassword"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak-service:8080/auth"
            - name: KEYCLOAK_REALM
              value: "fleet-management"
            # Topics Kafka consommés par ce service
            - name: KAFKA_TOPIC_VEHICULES
              value: "fleet.vehicules.events"
            - name: KAFKA_TOPIC_MAINTENANCE
              value: "fleet.maintenance.events"
            - name: KAFKA_TOPIC_GEOFENCING
              value: "fleet.geofencing.alerts"
            - name: KAFKA_TOPIC_NOTIFICATIONS
              value: "fleet.notifications"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
