apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-maintenance
  namespace: fleet-management
  labels:
    app: mf-maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mf-maintenance
  template:
    metadata:
      labels:
        app: mf-maintenance
    spec:
      containers:
        - name: mf-maintenance
          image: leiti20/mf-maintenance:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
