kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 15d
      
      additionalScrapeConfigs:
        - job_name: 'spring-actuator'
          metrics_path: '/actuator/prometheus'
          scrape_interval: 15s
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: 'fleet-.*-service' 
              action: keep
