server:
  port: 4000

spring:
  application:
    name: vehicule-service

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet_vehicles
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Kafka
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: vehicule-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
 # Keycloak / OAuth2
  security:
    oauth2:
      resourceserver:
        jwt:
          # Issuer pour valider le claim "iss" du token 
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9080/realms/fleet-management}
          # JWKS explicite pour éviter l'issuer mismatch Docker <-> localhost
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://host.docker.internal:9080/realms/fleet-management/protocol/openid-connect/certs}

# Custom properties
app:
  kafka:
    topic:
      vehicle-events: vehicle-events

# Actuator / Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTelemetry
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  service:
    name: vehicule-service

# Logging
logging:
  level:
    com.fleet: DEBUG
    org.springframework.kafka: INFO
    org.springframework.graphql: DEBUG
