apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://flotte-prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://flotte-loki:3100

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://flotte-jaeger:16686
