global:
  scrape_interval: 15s

scrape_configs:
  # On demande à Prometheus de venir récupérer les métriques depuis l'Otel Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['flotte-otel-collector:8889']
      
  # Scrape direct de Spring Boot Actuator (optionnel mais très recommandé)
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['vehicule-service:8081'] # Ajoutez les autres ici plus tard ('conducteur-service:3002', etc.)
