apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fleet-app.fullname" . }}
  labels:
    {{- include "fleet-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fleet-app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fleet-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "fleet-app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
