replicaCount: 1

image:
  repository: fleet-evenement-service
  tag: "latest"

service:
  port: 8084

env:
  SPRING_PROFILES_ACTIVE: docker
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/fleet-management
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-evenement:5432/evenements_db
