replicaCount: 1

image:
  repository: fleet-maintenance-service
  tag: "latest"

service:
  port: 8083

env:
  SPRING_PROFILES_ACTIVE: docker
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/fleet-management
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-maintenance:5432/maintenance_db
