replicaCount: 2

image:
  repository: fleet-vehicule-service # Nom de votre image docker
  tag: "latest"

service:
  port: 8081

env:
  SPRING_PROFILES_ACTIVE: docker
  KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/fleet-management
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicule_db
