apiVersion: v1
kind: Service
metadata:
  name: mf-conducteur
  namespace: fleet-management
  labels:
    app: mf-conducteur
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: mf-conducteur
