apiVersion: v1
kind: Service
metadata:
  name: frontend-shell
  namespace: fleet-management
  labels:
    app: frontend-shell
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: frontend-shell
