apiVersion: v1
kind: Secret
metadata:
  name: fleet-db-secrets
  namespace: fleet-management
type: Opaque
data:
  db-username: YWRtaW4=
  db-password: YWRtaW5wYXNzd29yZA==
  vehicule-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL3ZlaGljdWxlc19kYg==
  conducteur-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2NvbmR1Y3RldXJzX2Ri
  maintenance-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL21haW50ZW5hbmNlX2Ri
  evenement-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcG9zdGdyZXNxbDo1NDMyL2V2ZW5lbWVudHNfZGI=
  localisation-db-url: amRiYzpwb3N0Z3Jlc3FsOi8vdGltZXNjYWxlZGItcG9zdGdyZXNxbDo1NDMyL2xvY2FsaXNhdGlvbl9kYg==
---
apiVersion: v1
kind: Secret
metadata:
  name: fleet-kafka-secrets
  namespace: fleet-management
type: Opaque
data:
  bootstrap-servers: a2Fma2Etc2VydmljZTo5MDky
---
apiVersion: v1
kind: Secret
metadata:
  name: fleet-keycloak-secrets
  namespace: fleet-management
type: Opaque
data:
  admin-username: YWRtaW4=
  admin-password: YWRtaW4=
  realm: ZmxlZXQtbWFuYWdlbWVudA==